### ISSUE TITLE
Add Documentation About Group Assignment

### ISSUE THREAD

**Issue by rdegges** [oktadeveloper/okta.github.io#1292]
In our Widget quickstart docs, there is no mention of the Group assignments option: https://developer.okta.com/quickstart/#/widget/nodejs/generic

I find this pretty confusing as a user because as I'm reading through the tutorial, adding the settings, assigning a group seems like a security concern/point of interest to me. Since it isn't documented, it makes me worry about what it is set to by default (eg: "Everyone").

I propose we add in some documentation about this option, or at least a note explaining how it works.

**Comment by omgitstom** [comment]
I don't think this would be something in the quickstart but rather the next steps.  Quickstarts are supposed to be simple "get me authenticating".

I do think we need to merchandise the features of what you are using in the quickstarts better, like - "what should I do next?"

Would that resolve the issue or you?

**Comment by rdegges** [comment]
I think what might resolve it is to explicitly call this out in the quickstart.

We could say something like "Leave the Group Assignments option alone. This option can be used to only allow certain groups of users to log into your Application. We'll discuss this in depth <link here> later on </link>."

This way it doesn't scare people via omission, but also gives them so info so they aren't confused/worried.

**Comment by rdegges** [comment]
Closing this as it's in a diff repo now.
