### ISSUE TITLE
Authentication Guide, Update TOC to reference Application Type instead of OAuth Flow

### ISSUE THREAD

**Issue by omgitstom** [oktadeveloper/okta.github.io#1515]
Small optimization for TOC readability.  Looking at GA, users are clicking on the TOC multiple times to find the right flow because they do not know the difference between the flows.  I think we can clean this up by mentioning the intent of the flow in the TOC instead of the correct OAuth 2.0 speak.

What I mean, is change this:
![implementing_oauth_2_0_authentication___okta_developer](https://user-images.githubusercontent.com/3199093/33446705-c10d21b4-d5b5-11e7-8303-ac4e2ef077eb.png)

To:
![implementing_oauth_2_0_authentication___okta_developer](https://user-images.githubusercontent.com/3199093/33446716-ccb0c8ae-d5b5-11e7-8c84-ad926a37e270.png)

**Comment by jakubvul** [comment]
If we do this, that kind of looks like we'll have to rewrite the [Choosing a flow](https://developer.okta.com/authentication-guide/auth-overview/#choosing-an-oauth-20-flow) section, no? I don't think just changing the ToC is enough.

**Comment by nbarbettini** [comment]
I like this change. I agree with @jakubvul that it involves more than just changing the TOC, but I think it'd be a worthwhile improvement.

IMO, we'd need to also update:

* Each of those page titles. Some possibilties: "Server Side Web Flow with OAuth 2.0" or "OAuth 2.0 for server side web applications" with an h2 of "Authorization code flow"
* The table on [Implementing OAuth 2.0](https://developer.okta.com/authentication-guide/implementing-authentication/) would need to be switched around: Type of Application would be the link, OAuth 2.0 Flow would be text.
* Similarly, in [Choosing an OAuth 2.0 flow](https://developer.okta.com/authentication-guide/auth-overview/#choosing-an-oauth-20-flow), most of the text can probably stay the same. We can just flip around the hyperlink so Single-Page App is the link, not Implicit flow.

See also [OKTA-154996](https://oktainc.atlassian.net/browse/OKTA-154996) for another micro-improvement that reinforces the web/native/SPA/machine app type.

**Comment by nbarbettini** [comment]
Overall, I feel strongly that "the less OAuth jargon, the better". Here's why:

* Folks unfamiliar with OAuth jargon have no idea what "Authorization code flow" and "Implicit flow" are in the TOC. They will probably know what type of application they have.
* Folks familiar with OAuth jargon already know that code = web, implicit = SPA. They shouldn't be _more_ confused by less jargon.

There is a point where we could remove so much jargon that it starts increasing confusion again. IMO, we are far from it. 😄

**Comment by rdegges** [comment]
Closing this as this isn't managed in this repo any longer.
