### ISSUE TITLE
yourOktaDomain link should provide more contextual info

### ISSUE THREAD

**Issue by nbarbettini** [oktadeveloper/okta.github.io#1566]
When a `{yourOktaDomain}` link is transformed, it would be cool if there was a unique visual indicator. A dotted line perhaps:

![smart-macro-mock](https://user-images.githubusercontent.com/7525482/34142702-8da6bbb4-e43d-11e7-9139-d8e0bc777faa.png)
(#1565 applies here)

Then, a tooltip could be shown on hover that gives the user some more info about what it means:

```
This {yourOktaDomain} placeholder was automatically updated with your Okta organization URL.

If it doesn't look right, try one of these organization URLs instead:
https://...
```

If the user belongs to multiple orgs, the tooltip can show all of them.

**Comment by jmelberg-okta** [comment]
@nbarbettini Adding a note about the transformation is pretty straightforward. Where things get interesting is when we add support for an **account chooser**. If this becomes a priority, lets sync with @alexdahl-okta for some ideas.

**Comment by nbarbettini** [comment]
Makes sense 👍
