### ISSUE TITLE
Investigate syncing the styles from docs with blog for tables and blockquotes

### ISSUE THREAD

**Issue by mraible** [oktadeveloper/okta.github.io#1694]
The blockquotes in the docs are a lot tighter than they are in the blog. The tables are colored in blue too, whereas they're gray in the blog. 

Docs: https://developer.okta.com/docs/api/resources/users#response-parameters

<img width="760" alt="screen shot 2018-01-30 at 10 31 12 am" src="https://user-images.githubusercontent.com/17892/35581497-2c6eb5bc-05a9-11e8-9b89-a67f59f94ef1.png">

I recently removed the bottom border for tables on the blog so we could use tables to layout side-by-side images. We'll need to consider this if we add the doc's table styling to the blog.

**Comment by nbarbettini** [comment]
I like this idea. The crazy padding on blog blockquotes has always annoyed me:

![image](https://user-images.githubusercontent.com/7525482/35581777-b545abaa-05a1-11e8-9d2a-fb70b419f66f.png)

👍 from me for consistent styles between the blog and docs.

**Comment by mraible** [comment]
Here's what tables look like on the blog:

![image](https://user-images.githubusercontent.com/17892/35590250-7aa230e6-05c3-11e8-8a6e-112f23f393f6.png)
