### ISSUE TITLE
Social Login Documentation Updates

### ISSUE THREAD

**Issue by omgitstom** [oktadeveloper/okta.github.io#1771]
https://devforum.okta.com/t/okta-sign-in-widget-with-google-social-login/1252

We reference 4.10 for client_id, but it is step 4.9 

https://devforum.okta.com/t/reactjs-social-auth-examples-and-implementations/1524
In: https://developer.okta.com/authentication-guide/social-login/facebook

We tell them to update Site URL, but they should be setting Valid OAuth Redirect URIs

**Comment by omgitstom** [comment]
The link to google to create an application requires Authorized Redirect URI now, we need to point developers to go to the API console to create credentials for OAuth 2.0 
![credentials_-_my_project](https://user-images.githubusercontent.com/3199093/38269898-addbdf30-3736-11e8-9a40-28c41a6655cc.png)

**Comment by rdegges** [comment]
Closing this but pinging @robertjd in case he needs to take action in a different location.
