### ISSUE TITLE
Add Code Samples for PKCE

### ISSUE THREAD

**Issue by omgitstom** [oktadeveloper/okta.github.io#1830]
https://developer.okta.com/authentication-guide/implementing-authentication/auth-code-pkce
https://developer.okta.com/authentication-guide/implementing-authentication/auth-code-pkce#2-using-the-authorization-code-flow-with-pkce

Needs language code samples for generating the code verifier and code challenge in:

+ Javascript
+ Java
+ Swift
+ Obj-c

**Comment by jmelberg-okta** [comment]
I agree that this needs to be added for **Swift**, **Obj-C**, and **Java** (Android I assume). I think *if* we show a **Javascript** example - it needs to be coupled with the Mobile framework.

I'd suggest **not** showing PKCE with generic JS.

**Comment by omgitstom** [comment]
I think the generic JS would be useful because it is framework agnostic.

**Comment by jmelberg-okta** [comment]
Unfortunately we open up the developer's application to a [number of attack vectors](https://tools.ietf.org/html/rfc6819#section-4.1.2) if we recommend this. Long-lived tokens (especially refresh tokens) shouldn't be made available in public clients.

**Comment by bdemers** [comment]
JavaFX (or other desktop lib) would be interesting too: (originally requested in okta/okta-spring-boot#81)

**Comment by rdegges** [comment]
Closing this but pinging @robertjd in case there needs to be action taken in another repo.
