### ISSUE TITLE
`/authn` U2F example is incorrect

### ISSUE THREAD

**Issue by bdemers** [oktadeveloper/okta.github.io#1836]
I really like that the JS example is embedded in the `/authn` API (I was searching for exactly this), however it looks like the text `factorData.challenge.nonce` should be replaced with `challengeNonce`.
Section: https://developer.okta.com/docs/api/resources/authn#get-the-signed-assertion-from-the-u2f-token

**Comment by bdemers** [comment]
Testing out similar code now, I'll update the issue shortly

**Comment by bdemers** [comment]
NOTE: it is also missing a closing `);`

**Comment by rdegges** [comment]
Pinging @robertjd about this since he's managing this in a diff repo. Closing this one out.
