### ISSUE TITLE
Weird Styling on Docs

### ISSUE THREAD

**Issue by rdegges** [oktadeveloper/okta.github.io#1926]
I've always been curious about this: why do our quickstart docs look... so funky?

![screenshot from 2018-04-02 23-01-49](https://user-images.githubusercontent.com/90247/38231964-e7b2f378-36c9-11e8-8501-b60512658cb5.png)

There's not really a margin, it says "Server Setup" at the top of the page, and just generally looks really bad like maybe the CSS is messed up or something. Has anyone taken a look at this? oO

**Comment by jmelberg-okta** [comment]
Hey @rdegges - When our pages were redesigned last year, we decided to move the right-side navigation to the top of the page for specific screen sizes. Not only does this affect our quickstarts, but you'll see this in our API documentation as well.

@alexdahl-okta might have master plan for this in the works, but for now I'm going to close down this issue.

**Comment by robertjd** [comment]
We do have new comps to implement, but in the meantime we might have to fix this client/server selector in some way - it is quite broken

**Comment by rdegges** [comment]
Closing this as it isn't in this repo any longer.
