### ISSUE TITLE
Add test to ensure pages do NOT contain a dot `.` i.e. /foo-bar-2.0.html

### ISSUE THREAD

**Issue by bdemers** [oktadeveloper/okta.github.io#2023]
We have a page `blog/2018/03/16/build-react-native-authentication-oauth-2.0` that contains a dot in the path, this is not valid and prompts the user for a file download (when browsing)

This is the only page with a dot in the path (other then the file extension). We should add a test and fail the build if this case is detected.

Or something like this (but with an error message):
```bash
find dist/blog -type f | sed 's_\.html__' | grep -q '\.'; test $? -eq 1
```

**Comment by rdegges** [comment]
Going to close this as it's a temporary issue. We're going to move all posts from nonslashed URLs to slashed URLs, eg: `/some-post.blah` -> `/some-post.blah/` which will resolve the issue naturally.
