### ISSUE TITLE
link is broken

### ISSUE THREAD

**Issue by gabrielsroka** [oktadeveloper/okta.github.io#2057]
the link on
https://developer.okta.com/docs/api/resources/schemas
to 
"Okta Support Doc for ISO compliant Locale values"
https://support.okta.com/help/Documentation/Knowledge_Article/Universal-Directory-enforcement-of-ISO-compliant-Locale-values

is broken. i don't know what the new link is.

**Comment by rdegges** [comment]
Pinging @robertjd about this since his team manages this in a different repo now.
