### ISSUE TITLE
Add links to samples for Java and PHP

### ISSUE THREAD

**Issue by mraible** [oktadeveloper/okta.github.io#2076]
The quickstart guides for Node and .NET link to the samples. For example, [Node](https://developer.okta.com/quickstart/#/okta-sign-in-page/dotnet/aspnetcore) has:

> If you would prefer to download a complete sample application instead, please visit Express Sample Applications for Okta and follow those instructions.

The [Java](https://developer.okta.com/quickstart/#/okta-sign-in-page/java/spring) and [PHP](https://developer.okta.com/quickstart/#/okta-sign-in-page/php/generic) do not have this callout. This issue is to track adding them.

Another suggested improvement for Java/Spring: mention that if you don't have a project, go to [start.spring.io](https://start.spring.io) and create a project with x dependencies, or provide a curl/httpie command to do it.

**Comment by rdegges** [comment]
Getting rid of this since it is no longer managed in this repo, but pinging @robertjd in case this still needs updating.
