### ISSUE TITLE
Linting should use a cross-platform language

### ISSUE THREAD

**Issue by nbarbettini** [oktadeveloper/okta.github.io#2136]
The `npm run post-build-lint` command uses bash to execute this shell script: https://github.com/okta/okta.github.io/blob/source/scripts/post-build-lint.sh

Relying on bash means that it's impossible for non-*nix contributors to run or develop this script. We should investigate converting it to a Node script instead.

See: #2128 (blocked)

**Comment by rdegges** [comment]
Getting rid of this for now.
