### ISSUE TITLE
Add expected response to sample for add WS-Federation Application

### ISSUE THREAD

**Issue by laura-rodriguez** [oktadeveloper/okta.github.io#2141]
* Response is not provided as in other examples.
* Using the request example provided here: https://developer.okta.com/docs/api/resources/apps#request-example-7, the `groupName` of the response is `http://schemas.microsoft.com/ws/2008/06/identity/claims/role` when it was set to `null` in the request.

**Comment by rdegges** [comment]
I'm closing this one since these are all in a new repo now.
