### ISSUE TITLE
System Log > Postman collection has a wrong endpoint

### ISSUE THREAD

**Issue by laura-rodriguez** [oktadeveloper/okta.github.io#2178]
Get Log since date should be `{{url}}/api/v1/logs?since=2017-03-11` instead of `{{url}}/api/v1/events?since=2017-03-11`

Link: https://developer.okta.com/docs/api/resources/system_log#getting-started

**Comment by rdegges** [comment]
Pinging @robertjd about this since his team manages this in a new repo now =)
