### ISSUE TITLE
Update https://developer.okta.com/code/dotnet/ with the new Okta ASP.NET examples

### ISSUE THREAD

**Issue by laura-rodriguez** [oktadeveloper/okta.github.io#2214]
New examples Repo:
* https://github.com/okta/samples-aspnet
* https://github.com/okta/samples-aspnetcore

Also, there are related pages that will need an update too as now we have an Okta OIDC middleware for ASP.NET, i.e `code/dotnet/jwt-validation`.

**Comment by rdegges** [comment]
Closing this since it isn't managed in this repo any longer.
