### ISSUE TITLE
Add more SCIM overview info

### ISSUE THREAD

**Issue by nbarbettini** [oktadeveloper/okta.github.io#2487]
This page: _source/_reference/scim/index.md

Covers the SCIM protocol endpoints that Okta uses. It doesn't explain _when_ you'd use them. If we get feedback that the when/why would be helpful, we'll add more info. (Add a 👍 if this would be helpful to you!)

**Comment by rdegges** [comment]
Closing this but pinging @robertjd since his team manages this in a separate repo now =)
