### ISSUE TITLE
System Log errors inconsistent with the documentation

### ISSUE THREAD

**Issue by p-b--** [oktadeveloper/okta.github.io#2499]
Instead of opening multiple issues for each, I'll open one issue with inconsistencies between the documented error messages and what I received.

In most cases, where an error is supposed to occur it does, however it does so without the expected message or the expected error code.

### Incorrectly formatted `start_date` or `until`
**Query:** `curl -v -X GET -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: SSWS <auth_code>" "https://<instance>.oktapreview.com/api/v1/logs?since=foobar"`
**Query**: `curl -v -X GET -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: SSWS <auth_code>" "https://<instance>.oktapreview.com/api/v1/logs?until=01-01-2017"`
#### Expected:
HTTP Code: _unknown_
```
{
  "errorCode": "E0000001",
  "errorSummary": "Api validation failed: 'until': The date format in your query is not recognized. Please enter dates using ISO8601 string format.. 'until': must be a valid date-time or empty.",
  "errorId": "dd4998a1-2267-499b-9e4d-ec821fcc5ca9",
  "errorCauses": [
    {
      "errorSummary": "until: The date format in your query is not recognized. Please enter dates using ISO8601 string format."
    },
    {
      "errorSummary": "until: must be a valid date-time or empty."
    }
  ]
}
```
#### Received:
HTTP Code: 400
```
{
	"errorCode": "E0000030",
	"errorSummary": "The date format in your query is not recognized. Please enter dates using the Internet Date/Time Format profile of ISO 8601.",
	"errorId": "166639b0-a6a6-45c6-922e-f8d66d889498"
}
```
### Incorrectly formatted `filter`
**Query:** `curl -v -X GET -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: SSWS <auth code>" "https://<instance>.oktapreview.com/api/v1/logs?filter=display_message%20eqq%20%22create%20okta%20user%22"`
_Note: All incorrect filters display the same response._
#### Expected:
HTTP Code: 400
```
{
  "errorCode": "E0000053",
  "errorSummary": "Invalid filter 'display_message eqq \"Create okta user\"': Unrecognized attribute operator 'eqq' at position 16. Expected: eq,co,sw,pr,gt,ge,lt,le",
  "errorId": "eb83dfe1-6d76-458c-8c0c-f8df8fb7a24b"
}
```
#### Received:
HTTP Code: 400
```
{
	"errorCode": "E0000031",
	"errorSummary": "API validation failed: \"filter\": must be a valid SCIM filter expression.",
	"errorId": "ec44911d-51a9-4e2d-8ebe-e1be450a0d29"
}
```
### Invalid Field
**Query:** `curl -v -X GET -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: SSWS <auth code>" "https://<instance>.oktapreview.com/api/v1/logs?some_invalid_field=bar"`
#### Expected:
HTTP Code: 400
```
{
  "errorCode": "E0000053",
  "errorSummary": "field is not valid: some_invalid_field",
  "errorId": "ec93dhe2-6d76-458c-8c0c-f8df8fb7a24b"
}
```
#### Received:
HTTP Code: 200
`[]`

### `since` field older than 180 days
**Query:** `curl -v -X GET -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: SSWS <auth code>" "https://<instance>.oktapreview.com/api/v1/logs?limit=1&since=2015-01-01T00%3A00%3A00%2B01%3A00"`

_Note:_ This appears to be a documentation error as well. The [Data Retention](https://developer.okta.com/docs/api/resources/system_log#data-retention) section has the following info:

> Queries that exceed the retention period will succeed but only results that have a published timestamp within the window will be returned.

#### Expected
HTTP Code: _unknown_
```
{
  "errorCode": "E0000053",
  "errorSummary": "Invalid parameter: The since parameter is over 180 days prior to the current day.",
  "errorId": "55166534-b7d8-45a5-a4f6-3b38a5507046"
}
```
#### Received:
HTTP Code: 200
```
[{
	"actor": {
		"id": "sprak5dkywCi9PbVd0h7",
		"type": "SystemPrincipal",
		"alternateId": "system@okta.com",
		"displayName": "Okta System",
		"detailEntry": null
	},
...snip...
	"published": "2018-06-01T18:02:58.177Z",
	"securityContext": {
		"asNumber": null,
		"asOrg": null,
		"isp": null,
		"domain": null,
		"isProxy": null
	},
	"severity": "INFO",
...snip...
}]
```

Thanks!

**Comment by jakubvul** [comment]
Another thank you @p-b-- , I've passed this on to the System Log team.

**Comment by rdegges** [comment]
Going to close this as this info isn't in this repo any longer.
