### ISSUE TITLE
Missing parameter conditions for System Log API

### ISSUE THREAD

**Issue by p-b--** [oktadeveloper/okta.github.io#2500]
The `q` parameters only supports a maximum of 40 characters as per the [errors section](https://developer.okta.com/docs/api/resources/system_log#errors):

> A free form query that is too long:
> ```
> {
>   "errorCode": "E0000001",
>   "errorSummary": "Api validation failed: 'q': Freeform search cannot contain items longer than 40 characters. Please shorten the items in your search or use an advanced filter to query by specific fields."
> }
> ```
> 

Please update the [operations table](https://developer.okta.com/docs/api/resources/system_log#operations) to include that restriction.

**Comment by jakubvul** [comment]
Thanks @p-b-- , I've passed this on to the relevant team. 

At first glance, it seems that the actual restriction is that we have a limit of 40 characters per keyword, with a maximum of 10 keyword per query.

**Comment by p-b--** [comment]
You're right -- completely misread that particular part of it.

I've closed my existing PR and let you guys update it.

Can I ask how the file update process works? Do they update the file in github or is the update process handled another way?

**Comment by jakubvul** [comment]
The actual error message will be corrected in the backend. Our documentation updates all happen as Pull Requests to this repo.
