### ISSUE TITLE
Code Working in Localhost but doesn't work when pushed to cloud. 

### ISSUE THREAD

**Issue by saibharadwajavuggili** [oktadeveloper/okta.github.io#2955]
It throws me this error: 

  **No url passed to constructor. Required usage: new OktaAuth({url: https://sample.okta.com}).**

 I can extract the Login Page from OKTA Widget in my Local server, but pushed into the cloud it throws the error. Appreciate the help in advance.

**Comment by mraible** [comment]
Can you please provide some more information? Are you using a blog post tutorial or a sample app to get started creating your app? It helps us help you if you provide steps to reproduce the problem. Thanks!
