### ISSUE TITLE
Intermittent authorization code errors

### ISSUE THREAD

**Issue by mcandre** [oktadeveloper/okta.github.io#3000]
Not sure where else to post this. I can use Okta with my live web application in Chrome. But when I try to setup test HTTP calls with Postman, then Okta responds with HTTP status 400, complaining about invalid / expired authorization codes. This didn't happen so much a month ago, but it's happening more and more now. Any idea why?

Some community members suggest clock drift may play a role. I can't speak for the server time for the dev-#####.okta.com sandboxes, but at least my local Mac device has the time right.

**Comment by mraible** [comment]
Please don’t cross post. It creates more work for us when you post in two places. Our developer forums is the correct place to ask this. It appears you already asked this question there:

https://devforum.okta.com/t/getting-intermittent-authorization-code-errors/5839
