### ISSUE TITLE
Don't link me to the SCIM spec and say we support "most" filtering, just show me what Okta can do

### ISSUE THREAD

**Issue by omgitstom** [oktadeveloper/okta.github.io#879]
I'm unsure how this information is helpful.  Is Okta saying that we support most SCIM operators, but not all of them are listed in the docs?

http://developer.okta.com/docs/api/getting_started/design_principles.html#operators

It is probably best to remove it and make sure the list is correct to what we support.

**Comment by rdegges** [comment]
Pinging @robertjd about this as this is managed in a new repo now.
